[package]
name = "lsmdb"
description = "LSM Tree based Storage Engine"
authors = ["Nrishinghananda Roy <roynrishingha@gmail.com>"]
version = "0.1.0"
categories = ["data-structures", "database-implementations"]
keywords = ["database", "key-value-store", "key-value", "kv", "db"]
repository = "https://github.com/roynrishingha/lsmdb"
license = "MIT OR Apache-2.0"
readme = "README.md"
publish = true
edition = "2021"


[badges]
maintenance = { status = "experimental" }

[lib]
path = "src/lib.rs"

[dev-dependencies]
rand = "0.8"
